### ISSUE TITLE
Claims Dialect not correct

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/EPD-by-example#13]
in the example files [XUA_samples](https://github.com/ehealthsuisse/EPD-by-example/tree/main/XUA_samples) for XUA Requests
the dialect is not declared correct according to 1.6.4.2.4.2 Message Semantics in the [specification](https://www.bag.admin.ch/dam/bag/de/dokumente/nat-gesundheitsstrategien/strategie-ehealth/gesetzgebung-elektronisches-patientendossier/gesetze/anhang_5_ergaenzung_1_epdv_edi_ausgabe_4.pdf.download.pdf/EPDV-EDI_Anhang_5_E1_DE_Ausgabe_4.pdf);
`<wst:Claims Dialect="http://bag.admin.ch/epr/2017/annex/5/addendum/2">`
should be
`<wst:Claims Dialect="http://www.bag.admin.ch/epr/2017/annex/5/amendment/2">`

**Comment by msmock** [comment]
Fixed as suggested
