### ISSUE TITLE
Encoding of technical user ID

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/EPD-by-example#14]
In [the examples](https://github.com/ehealthsuisse/EPD-by-example/blob/main/XUA_samples/3_Get_X-User_Assertion_Response-Technical_User.xml#L39), the technical user ID is an OID and is URN-encoded: 
```xml
<saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
              NameQualifier="urn:e-health-suisse:technical-user-id">urn:oid:1.3.6.1.4.1.343</saml2:NameID>
```

The EPDV Annex 5.1 does not specify that the URN-encoding is needed:
> The <SubjectConfirmation> element MUST contain a <NameID> child element. The <NameID> element must convey the unique ID the technical user is registered within the community and NameQualifier "urn:e-health-suisse:technical-user-id".

Other OIDs have that specified. E.g.
> The <AttributeValue> child element MUST convey the value of the Home Community ID (an Object Identifier) assigned to the Community that is initiating the request, using the urn format (that is, “urn:oid:” appended with the OID).

> The identifier MUST be OID in the format of URN as registered in the healthcare provider directory.

So, is it optional, mandatory or forbidden to URN-encode the technical user ID if it's an OID?

**Comment by msmock** [comment]
Dear Quentin, the content format of the UserID is not specified in Annex 8. It may be an OID in URN-encoding but may appear in different formats depending on the Identity Provider.  Thus, URN-encoding is optional.
