### ISSUE TITLE
Errors in the ITI-43 Document Consumer audit message

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/EPD-by-example#15]
There are a few errors in the [ITI-43 Document Consumer audit message](https://github.com/ehealthsuisse/EPD-by-example/blob/main/samples/iti-43-log.xml):

Too many participants with `UserIsRequester="true"`: DICOM says ([PS3.15 A.5.2](https://dicom.nema.org/medical/dicom/current/output/chtml/part15/sect_A.5.2.html)):
> The system shall not identify multiple participants as UserIsRequestor. If there are several known requestors, the reporting system shall pick only one as UserIsRequestor.

In the example, there are two participants with `UserIsRequester="true"`.

There are too many ParticipantObjectIdentification for patient numbers: IHE says (3.43.6.1.1) 0..1 Patient (ParticipantObjectIdentification with `ParticipantObjectTypeCode="2"`). In the example, there are two. While it could theoretically be an extension, it's not specified in the Swiss requirements and it should be removed.

Technically, the order of elements is also wrong, but that's a mistake of IHE: human requestors usually go between the source and destination, except for this transaction.

The two human requestors seem valid according to the Swiss requirements.

**Comment by stephane-spahni** [comment]
Regarding the first point, do I understand correctly that UserIsRequester should be "false" for both?

> Used to identify which of the participants initiated the transaction being audited. If the audit source cannot determine which of the participants is the requestor, then the field shall be present with the value FALSE in all participants.

> The system shall not identify multiple participants as UserIsRequestor. If there are several known requestors, the reporting system shall pick only one as UserIsRequestor.

Regarding the second point, there is 1 ParticipantObjectTypeCode="1" and 1 ParticipantObjectTypeCode="3" --> ?

**Comment by qligier** [comment]
> Regarding the first point, do I understand correctly that UserIsRequester should be "false" for both?

See ongoing discussion with Dmytro: https://github.com/oehf/ipf/issues/419

> Regarding the second point, there is 1 ParticipantObjectTypeCode="1" and 1 ParticipantObjectTypeCode="3" --> ?

The one required by IHE is ParticipantObjectTypeCode="1". The one with ParticipantObjectTypeCode="3" is not specified anywhere, it probably is allowable as an extension but will only confuse implementers here.

**Comment by msmock** [comment]
Fixed by removing the UserIsRequester="true" attribute and removing the wrong articipantObjectIdentification. Kept the order, since in XML the order of the elements is not specified to be of relevance unless it is a list.
