### ISSUE TITLE
How many ActiveParticipants with XUA?

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/EPD-by-example#16]
In the example https://github.com/ehealthsuisse/EPD-by-example/blob/main/samples/iti-18-log.xml, we see 3 ActiveParticipants for an HCP (source, destination and XUA).

In the Annex 5.1, they show:
```xml
<ActiveParticipant UserID="alias2&lt;7601000000000@hcportal.demo.org&gt;" UserName="alias2&lt;7601000000000@hcportal.demo.org&gt;"/>
<ActiveParticipant UserID="7601000000000" UserName="Dr. Hans Muster">
  <RoleIDCode csd-code="HCP" codeSystemName="2.16.756.5.30.1.127.3.10.6" originalText="Healthcare Professional" />
</ActiveParticipant>
```
(By the way, there are some issues in this example that should be fixed too, the UserID is missing the proper &lt; and the first 7 of the id, the UserName has a space before the id)

In the example, the source and first XUA are merged:
```xml
<ActiveParticipant
  UserID="consumer.service.xy"
  UserIsRequestor="true"
  AlternativeUserID="EPD-PROJ-2020:1199"
  UserName="&lt;9801000050702@http://ith-icoserve.com/eHealthSolutionsSTS&gt;"
  NetworkAccessPointID="EPD-Proj-2020"
  NetworkAccessPointTypeCode="1">
  <RoleIDCode csd-code="110153" codeSystemName="DCM" displayName="Source" originalText="Source"/>
 </ActiveParticipant>
```

Is it wrong, required or optional/allowed?

Edit: In https://github.com/ehealthsuisse/EPD-by-example/blob/main/samples/iti-43-log.xml, we have 4 ActiveParticipants for an HCP.

Edit 2:
```
ActiveParticipant source
ActiveParticipant destination
ActiveParticipant UserName="alias<user@issuer>"
ActiveParticipant hcp
```
vs
```
ActiveParticipant source
ActiveParticipant destination & UserName="alias<user@issuer>"
ActiveParticipant hcp
```

**Comment by msmock** [comment]
Corrected the example
