### ISSUE TITLE
Source and destination inverted in ITI-43 audit message

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/EPD-by-example#17]
In https://github.com/ehealthsuisse/EPD-by-example/blob/main/samples/iti-43-log.xml, the source and destination are inverted, if we follow IHE specifications: https://profiles.ihe.net/ITI/TF/Volume2/ITI-43.html#3.43.6 (but those specs are definitely weird).

The source should be the SOAP endpoint, and the destination the primary system.

**Comment by msmock** [comment]
Done
