### ISSUE TITLE
ITI-41 sample does not pass validation

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/EPD-by-example#21]
Sample: https://github.com/ehealthsuisse/EPD-by-example/blob/main/samples/ITI-41_request.xml
Validation result: https://ehealthsuisse.ihe-europe.net/evs/report.seam?oid=1.3.6.1.4.1.12559.11.25.4.218220&standard=49

- Missing originalProviderRole: #10
- Wrong SubmissionSet.contentTypeCode value
- Wrong element order, or missing element (_Invalid content was found starting with element 'rim:Slot'. ..._)

**Comment by msmock** [comment]
Please provide a valid example for me to use it as example and comment it.
