### ISSUE TITLE
PIX V3 Feed example not in Agreement with EPDV-EDI_Anhang_5_E1_DE_Ausgabe_4 from  16. März 2021

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/EPD-by-example#4]
EPDV-EDI_Anhang_5_E1_DE_Ausgabe_4.pdf states in 1.7.1.1 Major Components of the Patient Registry Record Added/Revised Messages that Patient.id SHALL convey the patient’s local ID and the EPR-SPID 

![image](https://user-images.githubusercontent.com/2414516/131624848-b4bc81a4-80cf-46ff-8ff5-deb295c3fbfa.png)

Hoewer the PIX V3 has the following text:

>The asOtherId elements shall include the
>
>local ID the patient is registered in the primary system, with the OID of the primary system in the root attribute, and the ID >value in the extension attribute.
>
>the EPR-SPID with the OID of the ZAS in the root attribute, and the value in the extension attribute.

1. According to EPDV-EDI_Anhang_5_E1_DE_Ausgabe_4.pdf  should be moved to the patientPerson child element id ?
2. The example should be adjusted that the id Element with EPR-SPID is also added in the id Element
3. What should be provided in Other ID? The Annex specifies currently  id [1..*] (M)?

![image](https://user-images.githubusercontent.com/2414516/131626113-b79fa934-49b4-4ee5-a104-32b52a956f60.png)

**Comment by msmock** [comment]
Done
